#!/bin/bash

#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#  KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

#
# compile and launch a Cordova/iOS project to the simulator
#

set -e
LANG=C
CORDOVA_PATH=$( cd "$( dirname "$0" )" && pwd )
PROJECT_PATH=$( cd "$( dirname "$0" )/.." && pwd )


if [ "$1" != "" ]; then
	echo "Update file $PROJECT_PATH/AndroidManifest.xml to $1."
	VERSION=${1//./}
	sed -i -e "s/versionCode=\".*\"/versionCode=\"${VERSION}\"/g" "$PROJECT_PATH/AndroidManifest.xml"
	sed -i -e "s/versionName=\".*\"/versionName=\"$1\"/g" "$PROJECT_PATH/AndroidManifest.xml"
	echo 'test' > $PROJECT_PATH/space-e
	rm -rf "$PROJECT_PATH/AndroidManifest.xml-e"
	echo "updated version to $1 !"
fi
  



